### ISSUE TITLE
easy: rename settings to options

### ISSUE THREAD

**Issue by bobanko** [StepanoidTeam/battle-city-io#9]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/3473454/198632759-4a7b532d-fb43-4aa3-9de5-07eea38f1dad.png">

rename settings title to options, since settings barely fit the screen
also recolor options to be gray for option text and white for values
rename all occurences in code, settings → options

**Comment by SvetlanaVaskiv** [comment]
[done[](url)](url)
<img width="731" alt="Screenshot 2022-10-28 at 17 12 37" src="https://user-images.githubusercontent.com/87388027/198672042-4fed27ab-1731-4711-b693-c934afed3a50.png">
